name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Asia/Ho_Chi_Minh
          token: ${{ secrets.PERSONAL_PROFILE }}
          # languages
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          # isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # achievements
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          config_display: large
          config_order: isocalendar, languages
  actions-timeline:
    needs: [github-metrics]
    runs-on: ubuntu-latest
    steps:
    - uses: Kesin11/actions-timeline@v2
