name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"

  # (optional) Run workflow manually
  workflow_dispatch:

  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: generate metrics graph
        uses: lowlighter/metrics@latest
        with:
          config_timezone: Asia/Ho_Chi_Minh
          token: ${{ secrets.PERSONAL_PROFILE }}
          # languages
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          # isocalendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          # achievements
          plugin_achievements: no
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          config_display: large
          config_order: isocalendar, languages
          # using prebuilt docker image
          use_prebuilt_image: yes
          # commit timeline
          output_action: commit
          committer_branch: output
          committer_message: "chore: update metrics"
          # push gist
          # output_action: gist
          # committer_gist: bf0200489e03c11f9c8b68fc78ec1ba3

  actions-timeline:
    needs: [github-metrics]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Kesin11/actions-timeline@v2
